ads/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name="ads"

urlpatterns=[
	path('', views.AdListView.as_view(), name='all'),
    	path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    	
    	#success_url alternatively can be specified in CBV
    	path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    	path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    	path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    	path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    	path('ad/<int:pk>/comment',views.CommentCreateView.as_view(), name='ad_comment_create'),
        path('comment/<int:pk>/delete',views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
        path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
        path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

autos/urls.py
from django.urls import path
from . import views

app_name='autos'
urlpatterns=[
	path('', views.autosList.as_view(), name='autosList'),
	path('main/create', views.autosCreate.as_view(), name='autosCreate'),
	path('main/<int:pk>/update', views.autosEdit.as_view(), name='autosEdit'),
	path('main/<int:pk>/delete', views.autosDelete.as_view(), name='autosDelete'),
	
	path('lookup', views.makeList.as_view(), name='makeList'),
	path('lookup/create', views.makeCreate.as_view(), name='makeCreate'),
	path('lookup/<int:pk>/update', views.makeEdit.as_view(), name='makeEdit'),
	path('lookup/<int:pk>/delete', views.makeDelete.as_view(), name='makeDelete'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.views.generic import TemplateView

from django.contrib.auth import views as auth_views
from django.views.static import serve

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('ads/', include('ads.urls')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),                                                                                           
    url(r'^site/(?P<path>.*)$', serve, {'document_root': SITE_ROOT, 'show_indexes': True}, name='site_path'),
    path('', include('home.urls')),
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('hello/', include('hello.urls')),
    path('autos/', include('autos.urls')),
    path('accounts/', include('django.contrib.auth.urls')), #inbuilt authentication utlity from django
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('cats/', include('cats.urls')),   
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator
# Create your models here.

class Make(models.Model):
      name = models.CharField(max_length=200, 
      			      validators=[MinLengthValidator(2, "Name must be greater than 1 character")],
      			      help_text="Enter a Make ex: Dodge"
      			      )
      
      def __str__(self):
          '''String to represent the model'''
          return self.name
          
          
          
class Autos(models.Model):
      nickname = models.CharField(max_length=200,
      				   validators=[MinLengthValidator(2, "Enter more than 1 character")]
      				  )
      mileage = models.PositiveIntegerField()
      comments = models.CharField(max_length=300)
      make = models.ForeignKey("Make", on_delete=models.CASCADE, null=False)	
      
      
      def __str__(self):
          return self.nickname
      
      
#models are registered in admin list

autos/forms.py
from django.forms import ModelForm
from autos.models import Make


# Create the form class.
class MakeForm(ModelForm):
    class Meta:
        model = Make
        fields = '__all__'

autos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View

from autos.models import Autos, Make
# Create your views here.

class autosList(LoginRequiredMixin, View):
      def get(self, request):
    	  makeCount = Make.objects.all().count() #count of all objects in make model, refer autos.model.Make
    	  autosList = Autos.objects.all()         #all objects from autos.models.Autos
    	  
    	  context = {"makeCount": makeCount, "autosList":autosList}
    	  
    	  return render(request, "autos/autosList.html", context)


class autosCreate(LoginRequiredMixin, CreateView):
      model=Autos
      fields= "__all__"
      success_url= reverse_lazy("autos:autosList")

class autosEdit(LoginRequiredMixin, UpdateView):
      model = Autos
      fields = "__all__"
      success_url= reverse_lazy("autos:autosList")
    	  #return render(request, 'autos/autosedit.html')  --- not required as using generic class based views
    
    
class autosDelete(LoginRequiredMixin, DeleteView):
      model= Autos
      fields= "__all__"
      success_url= reverse_lazy("autos:autosList")
    	  #return render(request, 'autos/autosdelete.html')
    
# One just needs to specify which model to create Create View for and the fields. Then Class based CreateView will automatically try to find a template in app_name/modelname_form.html    

class makeList(LoginRequiredMixin, View):
      def get(self, request):
    	  makeList= Make.objects.all()
    	  context= {"makeList":makeList}
    	  
    	  return render(request, 'make/makeList.html', context)
    
    
class makeCreate(LoginRequiredMixin, CreateView):
      model= Make
      fields= "__all__"
      success_url= reverse_lazy("autos:autosList")
      	  
      	  
class makeEdit(LoginRequiredMixin, UpdateView):
      model= Make
      fields= "__all__"
      success_url= reverse_lazy("autos:autosList")
    	  #return render(request, 'make/makeedit.html')
    
    
class makeDelete(LoginRequiredMixin, DeleteView):    
      model= Make
      fields= "__all__"
      success_url= reverse_lazy("autos:autosList")
    	  #return render(request, 'make/makedelete.html')
    	  
    	  
    	  
#examples of views without using generic views

# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
#class MakeCreate(LoginRequiredMixin, View):
#    template = 'autos/make_form.html'
#    success_url = reverse_lazy('autos:all')

#    def get(self, request):
#        form = MakeForm()
#        ctx = {'form': form}
#        return render(request, self.template, ctx)

#    def post(self, request):
#        form = MakeForm(request.POST)
#        if not form.is_valid():
#            ctx = {'form': form}
#            return render(request, self.template, ctx)

#        make = form.save()
#        return redirect(self.success_url)


# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
#class MakeUpdate(LoginRequiredMixin, View):
 #   model = Make
 #   success_url = reverse_lazy('autos:all')
 #   template = 'autos/make_form.html'
#
 #   def get(self, request, pk):
 #       make = get_object_or_404(self.model, pk=pk)
 #       form = MakeForm(instance=make)
#        ctx = {'form': form}
 #       return render(request, self.template, ctx)
#
 #   def post(self, request, pk):
 #       make = get_object_or_404(self.model, pk=pk)
 #       form = MakeForm(request.POST, instance=make)
 #       if not form.is_valid():
 #           ctx = {'form': form}
 #           return render(request, self.template, ctx)
#
 #       form.save()
 #       return redirect(self.success_url)


#class MakeDelete(LoginRequiredMixin, View):
#    model = Make
#    success_url = reverse_lazy('autos:all')
#    template = 'autos/make_confirm_delete.html'
#
#   def get(self, request, pk):
#        make = get_object_or_404(self.model, pk=pk)
#        form = MakeForm(instance=make)
#        ctx = {'make': make}
#        return render(request, self.template, ctx)
#
#    def post(self, request, pk):
#        make = get_object_or_404(self.model, pk=pk)
#        make.delete()
#        return redirect(self.success_url)

autos/templates/autos/autosList.html
{%extends "base_bootstrap.html"%}

<html>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head> 
 
 <body>
   {%block content%}
    <h1>Autos List</h1>
    {%if autosList %}
    <ul>
     {%for auto in autosList%}
      <li>{{auto.nickname}} ({{auto.make}})
      	  (<a href="{% url 'autos:autosEdit' auto.id %}">Update</a>|
           <a href="{% url 'autos:autosDelete' auto.id %}">Delete</a>) <br/> 
           {{auto.comments}}({{auto.mileage}} miles)
      </li>
     {%endfor%} 
    </ul>
    
    {%else%}
     <p>There are no autos in library</p>
    {%endif%}
    
    <p>
     {%if makeCount > 0%}
      <a href="{%url 'autos:autosCreate'%}">Add an auto</a>
     {%else%}
      Please add a make before you add an auto.
     {%endif%}
    </p> 
    
    <p>
      <a href="{% url 'autos:makeList' %}">View makes</a> ({{makeCount}}) |
      <a href="{% url 'autos:makeCreate'%}">Add a make</a>
    </p>
   {%endblock%}
  </body>
 </html>   

autos/templates/autos/autos_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

autos/templates/autos/autos_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:autosList' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

autos/templates/autos/make_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

autos/templates/autos/make_create_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:autosList' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

autos/templates/autos/make_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:autosList' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}