ads/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name="ads"

urlpatterns=[
	path('', views.AdListView.as_view(), name='all'),
    	path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    	
    	#success_url alternatively can be specified in CBV
    	path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    	path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    	path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    	path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    	path('ad/<int:pk>/comment',views.CommentCreateView.as_view(), name='ad_comment_create'),
        path('comment/<int:pk>/delete',views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
        path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
        path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

cats/urls.py
from django.urls import include, path
from . import views

app_name="cats"
urlpatterns=[
             path("", views.CatList.as_view(), name="catList"),
             path("main/create", views.CatCreate.as_view(), name="catCreate"),
             path("main/<int:pk>/update", views.CatUpdate.as_view(), name="catUpdate"),
             path("main/<int:pk>/delete", views.CatDelete.as_view(), name="catDelete"),
             
             path("lookup", views.BreedList.as_view(), name="breedList"),
             path("lookup/create", views.BreedCreate.as_view(), name="breedCreate"),
             path("lookup/<int:pk>/update", views.BreedUpdate.as_view(), name="breedUpdate"),
             path("lookup/<int:pk>/delete", views.BreedDelete.as_view(), name="breedDelete"),
            ]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.views.generic import TemplateView

from django.contrib.auth import views as auth_views
from django.views.static import serve

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('ads/', include('ads.urls')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),                                                                                           
    url(r'^site/(?P<path>.*)$', serve, {'document_root': SITE_ROOT, 'show_indexes': True}, name='site_path'),
    path('', include('home.urls')),
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('hello/', include('hello.urls')),
    path('autos/', include('autos.urls')),
    path('accounts/', include('django.contrib.auth.urls')), #inbuilt authentication utlity from django
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('cats/', include('cats.urls')),   
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

cats/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
      name= models.CharField(max_length=200,
      			     validators=[MinLengthValidator(2,"Enter more than 1 character")]
      			     )
      
      def __str__(self):
          return self.name
          

class Cat(models.Model):
      nickname = models.CharField(max_length=200,
      				   validators=[MinLengthValidator(2, "Enter more than 1 character")]
      				   )
      
      weight = models.PositiveIntegerField()
      foods= models.CharField(max_length=300)
      breed= models.ForeignKey("Breed", on_delete=models.CASCADE, null= False)
      
      
      def __str__(self):
          return self.nickname 

cats/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

from cats.models import Cat, Breed

class CatList(LoginRequiredMixin, View):
      def get(self, request):
          breedCount = Breed.objects.all().count()
          catList = Cat.objects.all()
          
          context = {"catList":catList, "breedCount": breedCount}
          
          return render(request, "cats/catsList.html", context)
        

class CatCreate(LoginRequiredMixin, CreateView):
      model= Cat
      fields = "__all__"
      success_url = reverse_lazy("cats:catList")


class CatUpdate(LoginRequiredMixin, UpdateView):
      model= Cat
      fields = "__all__"
      success_url = reverse_lazy("cats:catList")
      
      
class CatDelete(LoginRequiredMixin, DeleteView):
      model= Cat
      fields = "__all__"
      success_url = reverse_lazy("cats:catList")
      

class BreedList(LoginRequiredMixin, View):
      def get(self, request):
          breedList = Breed.objects.all()
          
          context = {"breedList":breedList}
          
          return render(request, "cats/breedList.html", context)
          

class BreedCreate(LoginRequiredMixin, CreateView):
      model = Breed
      fields = "__all__"	#list of field "names(string)" of model
      success_url= reverse_lazy("cats:catList")
      

class BreedUpdate(LoginRequiredMixin, UpdateView):
      model = Breed
      fields = "__all__"
      success_url= reverse_lazy("cats:catList")
      

class BreedDelete(LoginRequiredMixin, DeleteView):
      model = Breed
      fields = "__all__"
      success_url= reverse_lazy("cats:catList")

cats/templates/cats/breedList.html
{% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 
 <body>
  
  {%block content%}
    <h1>Breed list</h1>
    {%if not breedList%}
      <p> No breeds found</p>
    {%else%}
     {%for breed in breedList%}
      <ul>
        <li>{{breed.name}}
            (<a href="{%url 'cats:breedUpdate' breed.id%}">Update</a>|
             <a href="{%url 'cats:breedDelete' breed.id%}">Delete</a>) </br>
        </li>
     {%endfor%}
      </ul>
    {%endif%}
     
     <p>
      <a href="{%url 'cats:breedCreate'%}">(Add a breed | </a>
      <a href="{%url 'cats:catList'%}">Back to Cats)</a>
     </p> 
  
   {%endblock%}
  </body>
 </html>     
         

cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 

{% block content %}
 
 <h1>Delete Auto</h1>

 <p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}
</html>

cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 
 <body>
  {%block content%}
   
   <form action="" method="post">
    {%csrf_token%}
    <table>
     {{form.as_table}}
    </table>
    
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location={%url 'cats:catList'%}; return false"; value="Cancel">
   </form>
  {%endblock%}
 </body>
</html>    
	 

cats/templates/cats/breed_update_form.html
{% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 
 <body>
  {%block content%}
   
   <form action="" method="post">
    {%csrf_token%}
    <table>
     {{form.as_table}}
    </table>
    
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location={%url 'cats:catList'%}; return false"; value="Cancel">
   </form>
  {%endblock%}
 </body>
</html>    
	 

cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 

{% block content %}
 
 <h1>Delete Cats</h1>

 <p>Are you sure you want to delete the cat: {{ cats }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}
</html>

cats/templates/cats/cat_form.html
 {% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 
 <body>
  {%block content%}
  
   <form action="" method="post">
    {%csrf_token%}
    <table>
     {{form.as_table}}
    </table>
    
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location={%url 'cats:catList'%}; return false"; value="Cancel">
   </form>
  {%endblock%}
 </body>
</html>    
	 

cats/templates/cats/cat_update_form.html
{% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
  <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 
 <body>
  {%block content%}
   
   <form action="" method="post">
    {%csrf_token%}
    <table>
     {{form.as_table}}
    </table>
    
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location={%url 'cats:catList'%}; return false"; value="Cancel">
   </form>
  {%endblock%}
 </body>
</html>    
	 

cats/templates/cats/catsList.html
{% extends "base_bootstrap.html" %}
<html lang=en>
 <head>
   <meta name="dj4e" content="f9f38a0177f16dcaa0d96bcd5b6d2440"> 
 </head>
 <body>
   
   {%block content%}
   	<h1>Cats List</h1>
   	<p>
   	{%if catList%}
   	  <ul>
   	  {%for cat in catList%}
   	    <li>{{cat.nickname}} ({{cat.breed}})
   	        (<a href="{% url 'cats:catUpdate' cat.id%}">Update</a>|
   	         <a href="{% url 'cats:catDelete' cat.id%}">Delete</a>)<br/>
   	    </li>
   	   {%endfor%}
   	   </ul>
   	 
   	 {%else%}
   	  No Cats Found
   	 {%endif%}
   	 </p>
   	 
   	 <p>
   	 {%if breedCount < 1 %}
   	   Please add a Breed first
   	 
   	 {%else%}
   	    <a href="{%url 'cats:catCreate'%}">Add a cat</a>
   	 {%endif%}
   	 </p> 
   	 
   	 <p>
   	   <a href="{%url 'cats:breedList'%}">View breeds</a> ({{breedCount}})| 
   	   <a href="{%url 'cats:breedCreate'%}">Add a breed</a>)
   	 </p>
   	  
   {%endblock%}
  </body>
</html>  	   
   	           